// VirtualPiano.net Compatible Mapping
// Linear progression: notes follow sequentially across keyboard rows
// This matches the standard used by most online piano sheet music

export const KEY_MAPPINGS = {
    "FULL": {
        // Lower Octaves (C2-B2) - Number Row
        "C2": "1",
        "C#2": "!",
        "D2": "2",
        "D#2": "@",
        "E2": "3",
        "F2": "4",
        "F#2": "$",
        "G2": "5",
        "G#2": "%",
        "A2": "6",
        "A#2": "^",
        "B2": "7",

        // Middle Octave (C3-B3) - Top Row (QWERTY)
        "C3": "8",
        "C#3": "*",
        "D3": "9",
        "D#3": "(",
        "E3": "0",
        "F3": "q",
        "F#3": "Q",
        "G3": "w",
        "G#3": "W",
        "A3": "e",
        "A#3": "E",
        "B3": "r",

        // Main Octave (C4-B4) - Home Row + Top Row continuation
        // C4 (Middle C) starts at 't'
        "C4": "t",
        "C#4": "T",
        "D4": "y",
        "D#4": "Y",
        "E4": "u",
        "F4": "i",
        "F#4": "I",
        "G4": "o",
        "G#4": "O",
        "A4": "p",
        "A#4": "P",
        "B4": "a",

        // Upper Octave (C5-B5) - Home Row continuation
        "C5": "s",
        "C#5": "S",
        "D5": "d",
        "D#5": "D",
        "E5": "f",
        "F5": "g",
        "F#5": "G",
        "G5": "h",
        "G#5": "H",
        "A5": "j",
        "A#5": "J",
        "B5": "k",

        // High Octave (C6-E6) - Bottom Row
        "C6": "l",
        "C#6": "L",
        "D6": "z",
        "D#6": "Z",
        "E6": "x",
        "F6": "c",
        "F#6": "C",
        "G6": "v",
        "G#6": "V",
        "A6": "b",
        "A#6": "B",
        "B6": "n",

        "C7": "m",

        // Very low notes with Ctrl
        "A0": "ctrl+1",
        "A#0": "ctrl+2",
        "B0": "ctrl+3",
        "C1": "ctrl+4",
        "C#1": "ctrl+5",
        "D1": "ctrl+6",
        "D#1": "ctrl+7",
        "E1": "ctrl+8",
        "F1": "ctrl+9",
        "F#1": "ctrl+0",
        "G1": "ctrl+q",
        "G#1": "ctrl+w",
        "A1": "ctrl+e",
        "A#1": "ctrl+r",
        "B1": "ctrl+t"
    },
    "LIMITED": {
        // Simplified mapping for main playing range (C3-C6)
        "C3": "8",
        "C#3": "*",
        "D3": "9",
        "D#3": "(",
        "E3": "0",
        "F3": "q",
        "F#3": "Q",
        "G3": "w",
        "G#3": "W",
        "A3": "e",
        "A#3": "E",
        "B3": "r",
        "C4": "t",
        "C#4": "T",
        "D4": "y",
        "D#4": "Y",
        "E4": "u",
        "F4": "i",
        "F#4": "I",
        "G4": "o",
        "G#4": "O",
        "A4": "p",
        "A#4": "P",
        "B4": "a",
        "C5": "s",
        "C#5": "S",
        "D5": "d",
        "D#5": "D",
        "E5": "f",
        "F5": "g",
        "F#5": "G",
        "G5": "h",
        "G#5": "H",
        "A5": "j",
        "A#5": "J",
        "B5": "k",
        "C6": "l",
        "C#6": "L",
        "D6": "z",
        "D#6": "Z",
        "E6": "x"
    }
};
